# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types: ["published"]

jobs:
  build-linux:
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up butler
      uses: jdno/setup-butler@v1.4.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -o ./release ./Pong.Desktop/Pong.Desktop.csproj
    - name: Create tar.gz package
      run: |
        tar -czvf linux-x64-${{ github.ref }}.tar.gz ./release
        butler push linux-x64-${{ github.ref }}.tar.gz yesseruser/pong:linux-x64
    - name: Publish linux to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: linux-x64-${{ github.ref }}.tar.gz
        
  build-windows:
    runs-on: windows-latest
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up butler
      uses: jdno/setup-butler@v1.4.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -o ./release --self-contained
    - name: Create zip package
      run: |
        7z a windows-x64-${{ github.ref }}.zip .\release\*
        butler push windows-x64-${{ github.ref }}.zip yesseruser/pong:win64
    - name: Publish windows to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: windows-x64-${{ github.ref }}.zip
  build-flatpak:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
